# .github/workflows/build-exe.yml
name: build-exe
on:
  push:
  workflow_dispatch:

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt pyinstaller

      # (optional) Show where files actually are
      - name: Debug tree (top 3 levels)
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Depth 3 | Select-Object FullName

      # Find a reasonable entrypoint automatically
      - name: Locate entrypoint
        shell: pwsh
        run: |
          $candidates = @(
            'src\main.py',
            'main.py',
            'app\main.py',
            'src\mytool\__main__.py'
          ) | ForEach-Object { Join-Path $PWD $_ }
          $entry = $candidates | Where-Object { Test-Path $_ } | Select-Object -First 1
          if (-not $entry) {
            Write-Host "No candidate found. Found these main-like files:"
            Get-ChildItem -Recurse -File -Include main.py,__main__.py | ForEach-Object FullName
            throw "Set your correct script path (e.g. src\main.py) or adjust the candidates."
          }
          "ENTRY=$entry" | Out-File -FilePath $env:GITHUB_ENV -Append
          Write-Host "Using entrypoint: $entry"

      # If you bundle config, ensure the path exists
      - name: Check add-data paths
        shell: pwsh
        run: |
          if (-not (Test-Path "config\config.yaml")) {
            Write-Warning "config\config.yaml not found; remove --add-data or fix the path."
          }

      # Build (PowerShell; no caret continuations needed)
      - name: Build onefile exe
        shell: pwsh
        run: pyinstaller --onefile --name mytool --add-data "config\config.yaml;config" "$env:ENTRY"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mytool-windows
          path: dist/mytool.exe
