name: Windows CI (no exe)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        shell: pwsh
        run: |
          python -m pip install -U pip
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }
          python -m pip install pytest

      - name: Pytest: discover and run
        shell: pwsh
        run: |
          Write-Host "pytest version:"
          python -m pytest --version

          Write-Host "`n== Collect-only =="
          python -m pytest --collect-only -q
          $collect = $LASTEXITCODE

          if ($collect -eq 5) {
            Write-Host "`nNo tests collected; skipping."
            exit 0
          }

          Write-Host "`n== Run tests (verbose) =="
          python -m pytest -vv --maxfail=1
          exit $LASTEXITCODE
